export type Language = "sk" | "en";

const text = {
	sk: {
		loginHeader: "Prihlásenie",
		login: "Prihlásiť sa",
		logout: "Odhlásiť",
		invalidEmail: "Neplatný email.",
		password: "Heslo",
		dropzone: "Potiahnite a pustite súbory s dátami sem, alebo kliknite a vyberte súbory.",
		addNewSportInitToastMsg: "Prebieha pridávanie nového športu...",
		addSportHeader: "Pridanie nového športu",
		autoGeneratedCode: "Kód je automaticky vygenerovaný systémom.",
		sportCodeInputPlaceholder: "Nový kód športu",
		sportTitleInputPlaceholder: "Názov športu",
		addNewSport: "Pridať nový šport"
	}
	,
	en: {
		loginHeader: "Log in",
		login: "Log in",
		logout: "Logout",
		invalidEmail: "Invalid email",
		password: "Password",
		dropzone: "Drag & drop files here, or click and select files.",
		addNewSportInitToastMsg: "Adding new sport...",
		addSportHeader: "Add new sport",
		autoGeneratedCode: "Code is automatically generated by the system.",
		sportCodeInputPlaceholder: "New code sport",
		sportTitleInputPlaceholder: "Sport name",
		addNewSport: "Add new sport"
	}
}

export default text;