Get ranking data.
---
parameters:
  - name: countryCode
    in: path
    type: string
responses:
  200:
    description: Ranking data.
    schema:
      type: "object"
      properties:
        message:
          type: string
        data:
          type: "object"
          properties:
            chart:
              type: array
              items:
                type: "object"
                properties:
                  code:
                    type: integer
                  title:
                    type: string
                  value:
                    type: integer
                  order:
                    type: integer
  400:
    description: Missing JSON header, missing required parameter or invalid value of some parameter.
  401:
    description: Authorization error.
  500:
    description: Internal server error or database error.